### ISSUE TITLE
[Bug] to_datetime

### ISSUE THREAD

**Issue by jidlin** [yagays/ja-timex#75]
# 🐛 Bug
## 説明

![image](https://user-images.githubusercontent.com/23120835/155081379-f609d331-b6c0-4475-8e32-e614da79a1b1.png)

## 実行環境
- **ja-timexのバージョン** :
- **Pythonのバージョン** :
- **OSの情報**:

**Comment by yagays** [comment]
I fix it. Next time, please write a document on how to reproduce the bug with your environment, thanks.
